#include "stdafx.h"
#include "Wall.h"
#include <windows.h>

wchar_t* wallType[10] = {
	L"  ",
	L"▓",
	L"〓",
	L"※",
	L"≈",
	L"≡",
	L"×",
	L"□",
	L"Ω",
	L"■"
};

WORD wallColor[10] = {
	0,
	FOREGROUND_RED|FOREGROUND_INTENSITY,
	FOREGROUND_BLUE|FOREGROUND_GREEN|FOREGROUND_RED|FOREGROUND_INTENSITY,
	FOREGROUND_INTENSITY,
	FOREGROUND_BLUE|FOREGROUND_INTENSITY,
	FOREGROUND_GREEN|FOREGROUND_INTENSITY,
	FOREGROUND_GREEN|FOREGROUND_BLUE|FOREGROUND_INTENSITY,
	BACKGROUND_GREEN|BACKGROUND_BLUE|BACKGROUND_RED|BACKGROUND_INTENSITY|FOREGROUND_BLUE|FOREGROUND_GREEN|FOREGROUND_RED|FOREGROUND_INTENSITY,
	FOREGROUND_BLUE|FOREGROUND_RED|FOREGROUND_INTENSITY,
	FOREGROUND_GREEN|FOREGROUND_BLUE|BACKGROUND_INTENSITY|FOREGROUND_INTENSITY|FOREGROUND_RED
};

CWall::CWall()
{
}


CWall::~CWall()
{
}
